/**
 * PDFBoogie end-to-end suite.
 *
 * Runs the *production build* (dist/, strict CSP) in headless Chromium and
 * exercises every tool with a variety of documents, images, drag & drop,
 * window resizing and list reordering. Outputs are downloaded through the
 * real browser download path and validated in Node (pdfjs / fflate / manual
 * binary checks).
 *
 * Fixtures: e2e/fixtures/*.pdf (generated by e2e/make-fixtures.mjs).
 * Images: generated in-page on <canvas> at exact dimensions.
 */
import { expect, type Page, test } from '@playwright/test';
import {
  captureDownload,
  clickButton,
  docxText,
  docxXml,
  dropFiles,
  dropFixtures,
  firstZipEntry,
  fixtureBytes,
  formFieldValues,
  jpegSize,
  makeCanvasImages,
  odtXml,
  pdfInfo,
  pngSize,
  webpSize,
  zipEntries,
} from './helpers';

/* ------------------------------------------------------------------ */
/* Small conveniences                                                  */
/* ------------------------------------------------------------------ */

const A4 = { w: 595, h: 842 }; // pt (± rounding from the 595.28/841.89 fixtures)

/** Expect no uncaught console errors or pageerrors on the page. */
function expectClean(page: Page) {
  const errors: string[] = [];
  page.on('pageerror', (e) => errors.push(String(e)));
  return () => {
    expect(errors, `uncaught errors: ${errors.join(' | ')}`).toHaveLength(0);
  };
}

/** Text of each file row (top to bottom). */
const rowNames = (page: Page) => page.locator('ul.filelist .file-row .file-name').allTextContents();

/** Wait until the file list has exactly `n` rows. */
async function expectRows(page: Page, n: number): Promise<void> {
  await expect(async () => {
    expect(await rowNames(page)).toHaveLength(n);
  }).toPass({ timeout: 15_000 });
}

/** Click move-up/down on row `i` (0-based). */
const moveRow = (page: Page, i: number, dir: 'up' | 'down') =>
  page
    .locator('ul.filelist .file-row')
    .nth(i)
    .locator('.file-actions button')
    .nth(dir === 'up' ? 0 : 1)
    .click();

const removeRow = (page: Page, i: number) =>
  page.locator('ul.filelist .file-row').nth(i).locator('.file-actions button').nth(2).click();

/** Assert no horizontal overflow at the current viewport. */
async function noHOverflow(page: Page) {
  const ok = await page.evaluate(
    () => Math.ceil(document.documentElement.scrollWidth) <= window.innerWidth + 1,
  );
  expect(ok, `horizontal overflow at ${await page.evaluate(() => window.innerWidth)}px`).toBe(true);
}

/* ------------------------------------------------------------------ */
/* 1. Site smoke — SSR content + responsive resizing                   */
/* ------------------------------------------------------------------ */

const ROUTES: Array<[string, RegExp]> = [
  ['/', /PDFBoogie/],
  ['/pdf-compress', /Compress PDF/],
  ['/pdf-merge', /Merge PDF/],
  ['/pdf-combine', /Combine pages/],
  ['/image-to-pdf', /Image to PDF/],
  ['/pdf-to-image', /PDF to [Ii]mage/],
  ['/pdf-to-doc', /PDF to Word/],
  ['/pdf-sign', /Sign/],
  ['/privacy', /Privacy/],
];

test.describe('site smoke', () => {
  for (const [path, h1] of ROUTES) {
    test(`${path} renders SSR h1, no horizontal overflow (1280)`, async ({ page }) => {
      const assertClean = expectClean(page);
      await page.goto(path);
      await expect(page.locator('h1').first()).toContainText(h1);
      await noHOverflow(page);
      // prerendered: content present without JS (meta title matches)
      await expect(page).toHaveTitle(/PDFBoogie|PDF/);
      assertClean();
    });

    test(`${path} holds layout at mobile (360) and tablet (768)`, async ({ page }) => {
      await page.setViewportSize({ width: 360, height: 740 });
      await page.goto(path);
      await expect(page.locator('h1').first()).toContainText(h1);
      await noHOverflow(page);

      await page.setViewportSize({ width: 768, height: 1024 });
      await page.waitForTimeout(150);
      await noHOverflow(page);
    });
  }

  test('unknown path returns 404; the prerendered 404 artifact renders', async ({ page }) => {
    const res = await page.goto('/definitely-not-a-page');
    expect(res?.status()).toBe(404);
    // A static server answers with its own 404; GitHub Pages is configured to serve
    // our prerendered 404.html for unknown paths — verify that artifact renders.
    await page.goto('/404.html');
    await expect(page.locator('h1')).toContainText(/404/);
  });

  test('static assets & SEO files are served', async ({ page }) => {
    for (const p of [
      '/sitemap.xml',
      '/robots.txt',
      '/og.png',
      '/favicon.svg',
      '/manifest.webmanifest',
      '/wasm/pdfcore_bg.wasm',
    ]) {
      const res = await page.request.get(p);
      expect(res.status(), `${p} → ${res.status()}`).toBe(200);
    }
    const sitemap = await page.request.get('/sitemap.xml');
    const body = await sitemap.text();
    expect(body).toContain('/pdf-to-doc');
  });
});

/* ------------------------------------------------------------------ */
/* 2. DropZone — drag & drop behaviour (merge page as reference)       */
/* ------------------------------------------------------------------ */

test.describe('dropzone & drag/drop', () => {
  test('dragenter sets the dragging state; drop clears it', async ({ page }) => {
    await page.goto('/pdf-merge');
    const dz = page.locator('.dropzone');
    expect(await dz.getAttribute('data-dragging')).not.toBe('true');

    await page.evaluate(() => {
      const el = document.querySelector('.dropzone')!;
      const dt = new DataTransfer();
      el.dispatchEvent(
        new DragEvent('dragenter', { bubbles: true, cancelable: true, dataTransfer: dt }),
      );
      el.dispatchEvent(
        new DragEvent('dragover', { bubbles: true, cancelable: true, dataTransfer: dt }),
      );
    });
    await expect(dz).toHaveAttribute('data-dragging', 'true');

    await page.evaluate(() => {
      const el = document.querySelector('.dropzone')!;
      el.dispatchEvent(new DragEvent('dragleave', { bubbles: true, cancelable: true }));
    });
    await expect(dz).toHaveAttribute('data-dragging', 'false');
  });

  test('drop one PDF → one row; drop a second batch appends (order kept)', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-merge');
    await dropFixtures(page, ['text-1p.pdf']);
    await expectRows(page, 1);
    expect(await rowNames(page)).toEqual(['text-1p.pdf']);

    await dropFixtures(page, ['text-5p.pdf', 'landscape-1p.pdf']);
    await expectRows(page, 3);
    expect(await rowNames(page)).toEqual(['text-1p.pdf', 'text-5p.pdf', 'landscape-1p.pdf']);
    assertClean();
  });

  test('dropping a non-PDF is rejected with a friendly error', async ({ page }) => {
    await page.goto('/pdf-merge');
    await dropFiles(page, [{ name: 'notes.txt', type: 'text/plain', data: [110, 105] }]);
    await expect(page.locator('.error-card')).toContainText('Not PDF or images: notes.txt');
    await expectRows(page, 0);
  });

  test('native <input type=file> path registers files', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-merge');
    await page
      .locator('.dz-input')
      .first()
      .setInputFiles([
        {
          name: 'text-1p.pdf',
          mimeType: 'application/pdf',
          buffer: Buffer.from(fixtureBytes('text-1p.pdf')),
        },
        {
          name: 'text-5p.pdf',
          mimeType: 'application/pdf',
          buffer: Buffer.from(fixtureBytes('text-5p.pdf')),
        },
      ]);
    await expectRows(page, 2);
    expect(await rowNames(page)).toEqual(['text-1p.pdf', 'text-5p.pdf']);
    assertClean();
  });

  test('dropzone tap target covers the zone (mobile-safe)', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 700 });
    await page.goto('/pdf-merge');
    const hit = await page.evaluate(() => {
      const dz = document.querySelector('.dropzone') as HTMLElement;
      const r = dz.getBoundingClientRect();
      const el = document.elementFromPoint(r.left + r.width / 2, r.top + r.height / 2);
      const input = document.querySelector('.dropzone input[type=file]') as HTMLElement | null;
      return el === input || (el !== null && input?.contains(el as Node));
    });
    expect(hit).toBe(true);
  });
});

/* ------------------------------------------------------------------ */
/* 3. Ordering — merge list reorder / remove + merge respects order    */
/* ------------------------------------------------------------------ */

test.describe('ordering (merge)', () => {
  test('up/down/remove controls reorder and prune the list', async ({ page }) => {
    await page.goto('/pdf-merge');
    await dropFixtures(page, ['text-1p.pdf', 'text-5p.pdf', 'landscape-1p.pdf']);
    await expectRows(page, 3);

    // move first down → [5p, 1p, landscape]
    await moveRow(page, 0, 'down');
    expect(await rowNames(page)).toEqual(['text-5p.pdf', 'text-1p.pdf', 'landscape-1p.pdf']);
    // move last up → [5p, landscape, 1p]
    await moveRow(page, 2, 'up');
    expect(await rowNames(page)).toEqual(['text-5p.pdf', 'landscape-1p.pdf', 'text-1p.pdf']);
    // remove middle → [5p, 1p]
    await removeRow(page, 1);
    await expectRows(page, 2);
    expect(await rowNames(page)).toEqual(['text-5p.pdf', 'text-1p.pdf']);
  });

  test('merged PDF page order matches the final list order (text markers)', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-merge');
    // [1p, 5p, landscape] → move 1p to the end → [5p, landscape, 1p]
    await dropFixtures(page, ['text-1p.pdf', 'text-5p.pdf', 'landscape-1p.pdf']);
    await expectRows(page, 3);
    await moveRow(page, 0, 'down'); // 1p → index 1: [5p, 1p, landscape]
    await moveRow(page, 1, 'down'); // 1p → index 2: [5p, landscape, 1p]
    expect(await rowNames(page)).toEqual(['text-5p.pdf', 'landscape-1p.pdf', 'text-1p.pdf']);

    const pdf = await captureDownload(page, () =>
      clickButton(page, /^Merge 3 files into one PDF$/),
    );
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(7); // 5 + 1 + 1
    const texts = info.pages.map((p) => p.text);
    // pages 1-5 from text-5p, page 6 landscape, page 7 text-1p
    expect(texts[0]!).toContain('MARK-P1');
    expect(texts[4]!).toContain('MARK-P5');
    expect(texts[5]!).toContain('MARK-LANDSCAPE');
    expect(texts[6]!).toContain('MARK-ONE');
    assertClean();
  });

  test('mixing images + PDF: images get the chosen page size, PDFs keep theirs', async ({
    page,
  }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-merge');
    await makeCanvasImages(page, [
      { name: 'img-a.jpg', mime: 'image/jpeg', w: 600, h: 400, paint: 'hgrad' },
      { name: 'img-b.png', mime: 'image/png', w: 400, h: 600, paint: 'vgrad' },
    ]);
    await dropFixtures(page, ['text-1p.pdf']);
    await expectRows(page, 3);
    await page.selectOption('#mergePageSize', 'a4');

    const pdf = await captureDownload(page, () =>
      clickButton(page, /^Merge 3 files into one PDF$/),
    );
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(3);
    const near = (a: number, b: number, tol = 2) => Math.abs(a - b) <= tol;
    // both image pages are A4 portrait; the PDF page keeps A4 too (fixture is A4)
    for (const pg of info.pages) {
      expect(near(pg.w, A4.w) && near(pg.h, A4.h), `page ${pg.w}×${pg.h}`).toBe(true);
    }
    assertClean();
  });

  test('encrypted PDF in merge → friendly error, no download', async ({ page }) => {
    await page.goto('/pdf-merge');
    await dropFixtures(page, ['text-1p.pdf', 'encrypted.pdf']);
    await expectRows(page, 2);
    await clickButton(page, /^Merge 2 files into one PDF$/);
    await expect(page.locator('.error-card')).toContainText(/password|protected/i);
    await expect(page.locator('.result-card')).toHaveCount(0);
  });
});

/* ------------------------------------------------------------------ */
/* 4. Combine (n-up)                                                    */
/* ------------------------------------------------------------------ */

test.describe('combine pages (n-up)', () => {
  test('page tiles render; selecting 2,4,5 at 2-up → 2 sheets', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-combine');
    await dropFixtures(page, ['text-5p.pdf']);
    await expect(page.locator('.page-tile')).toHaveCount(5);
    // default = all selected
    expect(await page.locator('.page-tile[aria-pressed="true"]').count()).toBe(5);

    // unselect all, then pick 2, 4, 5
    await clickButton(page, /^None$/);
    expect(await page.locator('.page-tile[aria-pressed="true"]').count()).toBe(0);
    await page.locator('.page-tile', { hasText: /^2$/ }).click();
    await page.locator('.page-tile', { hasText: /^4$/ }).click();
    await page.locator('.page-tile', { hasText: /^5$/ }).click();
    expect(await page.locator('.page-tile[aria-pressed="true"]').count()).toBe(3);

    await page.selectOption('#grid', '2');
    const pdf = await captureDownload(page, () => clickButton(page, /^Combine 3 pages$/));
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(2); // ceil(3/2)
    expect(Math.round(info.pages[0]!.w)).toBeCloseTo(A4.w, -1);
    assertClean();
  });

  test('all 5 pages: 4-up → 2 sheets; 16-up → 1 sheet', async ({ page }) => {
    await page.goto('/pdf-combine');
    await dropFixtures(page, ['text-5p.pdf']);
    await page.selectOption('#grid', '4');
    const pdf = await captureDownload(page, () => clickButton(page, /^Combine 5 pages$/));
    expect((await pdfInfo(pdf)).pages).toHaveLength(2); // ceil(5/4)

    // restart with the same file, switch grid, recombine
    await clickButton(page, /Adjust and combine again/);
    await page.selectOption('#grid', '16');
    const pdf2 = await captureDownload(page, () => clickButton(page, /^Combine 5 pages$/));
    expect((await pdfInfo(pdf2)).pages).toHaveLength(1); // ceil(5/16)
  });

  test('9-up landscape sheet: output page is landscape A4', async ({ page }) => {
    await page.goto('/pdf-combine');
    await dropFixtures(page, ['text-5p.pdf']);
    await page.selectOption('#grid', '9');
    await page.selectOption('#sheetSize', 'a4');
    await page.selectOption('#orientation', 'landscape');
    const pdf = await captureDownload(page, () => clickButton(page, /^Combine 5 pages$/));
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(1);
    expect(info.pages[0]!.w).toBeGreaterThan(info.pages[0]!.h);
    expect(Math.round((info.pages[0]!.w / 842) * 10)).toBe(10); // ~842pt wide
  });

  test('None selected → combine button disabled', async ({ page }) => {
    await page.goto('/pdf-combine');
    await dropFixtures(page, ['text-5p.pdf']);
    await clickButton(page, /^None$/);
    await expect(page.locator('button', { hasText: /Combine selected/ })).toBeDisabled();
  });
});

/* ------------------------------------------------------------------ */
/* 5. Image → PDF                                                      */
/* ------------------------------------------------------------------ */

test.describe('image to PDF', () => {
  test('4 canvas images → 4 pages; fit pages match image aspect (pt = px×0.75)', async ({
    page,
  }) => {
    const assertClean = expectClean(page);
    await page.goto('/image-to-pdf');
    await makeCanvasImages(page, [
      { name: 'a.png', mime: 'image/png', w: 800, h: 600, paint: 'solid', color: [200, 60, 60] },
      { name: 'b.png', mime: 'image/png', w: 600, h: 800, paint: 'solid', color: [60, 120, 200] },
      { name: 'c.png', mime: 'image/png', w: 1000, h: 400, paint: 'quarters' },
      { name: 'd.png', mime: 'image/png', w: 256, h: 256, paint: 'solid', color: [60, 180, 90] },
    ]);
    await expectRows(page, 4);

    const pdf = await captureDownload(page, () =>
      clickButton(page, /^Combine 4 images into a PDF$/),
    );
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(4);
    const near = (a: number, b: number, tol = 2) => Math.abs(a - b) <= tol;
    expect(near(info.pages[0]!.w, 600) && near(info.pages[0]!.h, 450)).toBe(true); // 800×600 px
    expect(near(info.pages[1]!.w, 450) && near(info.pages[1]!.h, 600)).toBe(true); // 600×800 px
    expect(near(info.pages[2]!.w, 750) && near(info.pages[2]!.h, 300)).toBe(true); // 1000×400 px
    expect(near(info.pages[3]!.w, 192) && near(info.pages[3]!.h, 192)).toBe(true); // 256×256 px
    assertClean();
  });

  test('reordering changes output page order', async ({ page }) => {
    await page.goto('/image-to-pdf');
    await makeCanvasImages(page, [
      { name: 'a.png', mime: 'image/png', w: 800, h: 400, paint: 'solid', color: [200, 60, 60] },
      { name: 'b.png', mime: 'image/png', w: 400, h: 800, paint: 'solid', color: [60, 120, 200] },
      { name: 'c.png', mime: 'image/png', w: 500, h: 500, paint: 'solid', color: [90, 90, 200] },
    ]);
    await expectRows(page, 3);
    // move last to front: [a,b,c] → [a,c,b] → [c,a,b]
    await moveRow(page, 2, 'up'); // c → index 1
    await moveRow(page, 1, 'up'); // c → index 0
    expect(await rowNames(page)).toEqual(['c.png', 'a.png', 'b.png']);

    const pdf = await captureDownload(page, () =>
      clickButton(page, /^Combine 3 images into a PDF$/),
    );
    const info = await pdfInfo(pdf);
    const near = (a: number, b: number, tol = 2) => Math.abs(a - b) <= tol;
    // first page now the 500×500 image → 375×375 pt
    expect(near(info.pages[0]!.w, 375) && near(info.pages[0]!.h, 375)).toBe(true);
    // second page the 800×400 image → 600×300 pt
    expect(near(info.pages[1]!.w, 600) && near(info.pages[1]!.h, 300)).toBe(true);
  });

  test('A4 page size normalizes every page', async ({ page }) => {
    await page.goto('/image-to-pdf');
    await makeCanvasImages(page, [
      { name: 'a.png', mime: 'image/png', w: 900, h: 300, paint: 'solid' },
      { name: 'b.png', mime: 'image/png', w: 300, h: 900, paint: 'solid', color: [0, 150, 150] },
    ]);
    await expectRows(page, 2);
    await page.selectOption('#pageSize', 'a4');
    const pdf = await captureDownload(page, () =>
      clickButton(page, /^Combine 2 images into a PDF$/),
    );
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(2);
    for (const pg of info.pages) {
      expect(Math.abs(pg.w - A4.w)).toBeLessThanOrEqual(2);
      expect(Math.abs(pg.h - A4.h)).toBeLessThanOrEqual(2);
    }
  });

  test('JPEG and WebP inputs both produce a valid multi-page PDF', async ({ page }) => {
    await page.goto('/image-to-pdf');
    await makeCanvasImages(page, [
      { name: 'a.jpg', mime: 'image/jpeg', w: 700, h: 500, paint: 'quarters' },
      { name: 'b.webp', mime: 'image/webp', w: 500, h: 700, paint: 'hgrad' },
    ]);
    await expectRows(page, 2);
    const pdf = await captureDownload(page, () =>
      clickButton(page, /^Combine 2 images into a PDF$/),
    );
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(2);
  });

  test('removing an image before convert drops its page', async ({ page }) => {
    await page.goto('/image-to-pdf');
    await makeCanvasImages(page, [
      { name: 'a.png', mime: 'image/png', w: 400, h: 300, paint: 'solid' },
      { name: 'b.png', mime: 'image/png', w: 300, h: 400, paint: 'solid', color: [200, 100, 0] },
    ]);
    await expectRows(page, 2);
    await removeRow(page, 0);
    await expectRows(page, 1);
    expect(await rowNames(page)).toEqual(['b.png']);
    const pdf = await captureDownload(page, () =>
      clickButton(page, /^Combine 1 image into a PDF$/),
    );
    expect((await pdfInfo(pdf)).pages).toHaveLength(1);
  });
});

/* ------------------------------------------------------------------ */
/* 6. PDF → Image                                                       */
/* ------------------------------------------------------------------ */

test.describe('PDF to image', () => {
  test('single page → PNG at 96 DPI with correct pixel size', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-to-image');
    await dropFixtures(page, ['text-1p.pdf']);
    await page.selectOption('#fmt', 'png');
    await page.selectOption('#dpi', '96');
    const png = await captureDownload(page, () => clickButton(page, /Convert .* to PNG/));
    const size = pngSize(png);
    expect(size).not.toBeNull();
    // A4 595.28×841.89 pt at 96 dpi → 794×1123 px
    expect(Math.abs(size!.w - 794)).toBeLessThanOrEqual(2);
    expect(Math.abs(size!.h - 1123)).toBeLessThanOrEqual(2);
    assertClean();
  });

  test('page subset 2–4 → ZIP with 3 JPEG entries (150 DPI)', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-to-image');
    await dropFixtures(page, ['text-5p.pdf']);
    await page.selectOption('#fmt', 'jpeg');
    await page.selectOption('#dpi', '150');
    await page.locator('input[aria-label="First page"]').fill('2');
    await page.locator('input[aria-label="Last page"]').fill('4');
    const zipBytes = await captureDownload(page, () =>
      // CTA includes the page count: "Convert pages 2–4 (3) to JPEG"
      clickButton(page, /Convert pages 2[\u2013-]4 \(3\) to JPEG/),
    );
    const entries = zipEntries(zipBytes);
    const names = Object.keys(entries);
    expect(names).toHaveLength(3);
    for (const n of names) {
      expect(jpegSize(entries[n]!)).not.toBeNull();
    }
    // page 3 is the 400×400 pt square → near-square JPEG at 150dpi (≈833×833)
    const third = names.find((n) => /3/.test(n))!;
    const s = jpegSize(entries[third]!)!;
    expect(Math.abs(s.w - s.h)).toBeLessThanOrEqual(4);
    assertClean();
  });

  test('WebP output carries the RIFF/WEBP header', async ({ page }) => {
    await page.goto('/pdf-to-image');
    await dropFixtures(page, ['landscape-1p.pdf']);
    await page.selectOption('#fmt', 'webp');
    await page.selectOption('#dpi', '96');
    const webp = await captureDownload(page, () => clickButton(page, /Convert .* to WebP/));
    expect(webpSize(webp)).not.toBeNull();
  });

  test('300 DPI landscape page → width > height', async ({ page }) => {
    await page.goto('/pdf-to-image');
    await dropFixtures(page, ['landscape-1p.pdf']);
    await page.selectOption('#fmt', 'png');
    await page.selectOption('#dpi', '300');
    const png = await captureDownload(page, () => clickButton(page, /Convert .* to PNG/));
    const s = pngSize(png)!;
    expect(s.w).toBeGreaterThan(s.h);
    // 841.89pt at 300dpi ≈ 3508px
    expect(Math.abs(s.w - 3508)).toBeLessThanOrEqual(6);
  });
});

/* ------------------------------------------------------------------ */
/* 7. PDF → Word / ODT                                                 */
/* ------------------------------------------------------------------ */

test.describe('PDF to doc', () => {
  test('text-5p → docx: all markers, 4 page breaks, Heading1 detected', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-to-doc');
    await dropFixtures(page, ['text-5p.pdf']);
    const docx = await captureDownload(page, () => clickButton(page, /Convert to \.docx/));
    const text = docxText(docx);
    for (const m of ['MARK-P1', 'MARK-P2', 'MARK-P3', 'MARK-P4', 'MARK-P5']) {
      expect(text, `missing ${m}`).toContain(m);
    }
    const xml = docxXml(docx);
    const breaks = (xml.match(/w:br w:type="page"/g) ?? []).length;
    expect(breaks).toBe(4); // 5 pages → 4 breaks
    expect(xml).toContain('Heading1'); // 24pt "Title One"
    assertClean();
  });

  test('text-1p → odt: valid ODF, mimetype first + stored, text present', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-to-doc');
    await dropFixtures(page, ['text-1p.pdf']);
    await page.selectOption('#docfmt', 'odt');
    const odt = await captureDownload(page, () => clickButton(page, /Convert to \.odt/));
    const first = firstZipEntry(odt);
    expect(first.name).toBe('mimetype');
    expect(first.method).toBe(0); // stored, per ODF
    const content = odtXml(odt, 'content.xml');
    expect(content).toContain('MARK-ONE');
    assertClean();
  });

  test('scan (no text layer) → 0 paragraphs, valid doc, no crash', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-to-doc');
    await dropFixtures(page, ['scan-2p.pdf']);
    await page.selectOption('#docfmt', 'odt');
    const odt = await captureDownload(page, () => clickButton(page, /Convert to \.odt/));
    // must be a valid archive with a content part (even if nearly empty)
    const content = odtXml(odt, 'content.xml');
    expect(content).toContain('office:text');
    // UI still shows a result (0 paragraphs) rather than an error card
    await expect(page.locator('.result-card')).toHaveCount(1);
    assertClean();
  });
});

/* ------------------------------------------------------------------ */
/* 8. Compress                                                         */
/* ------------------------------------------------------------------ */

test.describe('compress', () => {
  test('lossless: valid PDF, page count preserved (text-5p)', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-compress');
    await dropFixtures(page, ['text-5p.pdf']);
    const pdf = await captureDownload(page, () => clickButton(page, /Compress \(lossless\)/));
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(5);
    assertClean();
  });

  test('lossless on image-heavy: 3 valid pages', async ({ page }) => {
    await page.goto('/pdf-compress');
    await dropFixtures(page, ['image-heavy-3p.pdf']);
    const pdf = await captureDownload(page, () => clickButton(page, /Compress \(lossless\)/));
    expect((await pdfInfo(pdf)).pages).toHaveLength(3);
  });

  test('strong 96 DPI on image-heavy → smaller than input, 3 pages', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-compress');
    await dropFixtures(page, ['image-heavy-3p.pdf']);
    const inputSize = await page.evaluate(async () =>
      (await fetch('/e2e/fixtures/image-heavy-3p.pdf')).arrayBuffer().then((b) => b.byteLength),
    );
    // enable strong mode
    await page.locator('label.toggle input[type=checkbox]').check();
    await page.selectOption('#cdpi', '96');
    const pdf = await captureDownload(page, () => clickButton(page, /Compress \(strong\)/));
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(3);
    expect(pdf.byteLength, 'strong output should shrink a raster-heavy PDF').toBeLessThan(
      inputSize,
    );
    assertClean();
  });

  test('encrypted PDF → friendly error, no crash', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-compress');
    await dropFixtures(page, ['encrypted.pdf']);
    await clickButton(page, /Compress \(lossless\)/);
    await expect(page.locator('.error-card')).toBeVisible();
    assertClean();
  });

  test('quality slider + value do not overlap at 360px', async ({ page }) => {
    await page.setViewportSize({ width: 360, height: 740 });
    await page.goto('/pdf-compress');
    await dropFixtures(page, ['text-1p.pdf']);
    await page.locator('label.toggle input[type=checkbox]').check(); // show the slider row
    const row = page.locator('.range-row').first();
    const slider = row.locator('input[type=range]');
    const out = row.locator('output');
    const sBox = (await slider.boundingBox())!;
    const oBox = (await out.boundingBox())!;
    expect(oBox.x + oBox.width, 'value within viewport').toBeLessThanOrEqual(361);
    expect(oBox.x, 'value does not overlap the slider').toBeGreaterThanOrEqual(
      sBox.x + sBox.width - 2,
    );
  });
});

/* ------------------------------------------------------------------ */
/* 9. Sign & Fill                                                       */
/* ------------------------------------------------------------------ */

test.describe('sign & fill', () => {
  test('form panel lists all four fields', async ({ page }) => {
    await page.goto('/pdf-sign');
    await dropFixtures(page, ['form.pdf']);
    // the form scan is async — wait for the last field to appear
    await expect(page.locator('.field > span[title="country"]')).toBeVisible();
    const names = await page
      .locator('.field > span[title]')
      .evaluateAll((els) => els.map((e) => e.getAttribute('title')));
    expect(names).toEqual(expect.arrayContaining(['name', 'email', 'agree', 'country']));
  });

  test('fill text + checkbox + dropdown → apply → values persist in the PDF', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-sign');
    await dropFixtures(page, ['form.pdf']);
    await expect(page.locator('.field:has(span[title="name"]) input')).toBeVisible();
    await page.locator('.field:has(span[title="name"]) input').fill('Ada Lovelace');
    await page.locator('.field:has(span[title="email"]) input').fill('ada@example.com');
    // custom toggle: the visible control is the knob (the input is visually
    // hidden but real) — clicking the knob is what a user does
    await page.locator('.field:has(span[title="agree"]) .toggle .knob').click();
    await expect(
      page.locator('.field:has(span[title="agree"]) input[type=checkbox]'),
    ).toBeChecked();
    await page.locator('.field:has(span[title="country"]) select').selectOption('DE');
    await clickButton(page, /Apply form fill/);

    // form-only download is now allowed
    const pdf = await captureDownload(page, () => clickButton(page, /Download filled PDF/));
    const values = await formFieldValues(pdf);
    expect(values.name).toBe('Ada Lovelace');
    expect(values.email).toBe('ada@example.com');
    expect(values.agree).toBe(true);
    expect(String(values.country)).toBe('DE');
    assertClean();
  });

  test('drawn signature: draw → use → place on page → download a bigger valid PDF', async ({
    page,
  }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-sign');
    await dropFixtures(page, ['text-1p.pdf']);
    // draw a zigzag on the signature pad
    const pad = page.locator('canvas.sig-pad');
    const box = (await pad.boundingBox())!;
    await page.mouse.move(box.x + 15, box.y + box.height / 2);
    await page.mouse.down();
    for (let i = 1; i <= 14; i += 1) {
      await page.mouse.move(box.x + 15 + i * 12, box.y + box.height / 2 + (i % 2 === 0 ? -14 : 14));
    }
    await page.mouse.up();
    await clickButton(page, /^Use this signature$/);
    await expect(page.locator('.sig-preview img')).toHaveCount(1);
    // placing mode starts automatically on "Use this signature"
    const stage = page.locator('.stage[data-page="1"]');
    const sbox = (await stage.boundingBox())!;
    await page.mouse.click(sbox.x + sbox.width / 2, sbox.y + sbox.height * 0.75);
    await expect(page.locator('.stamp')).toHaveCount(1);

    const inputSize = await page.evaluate(async () =>
      (await fetch('/e2e/fixtures/text-1p.pdf')).arrayBuffer().then((b) => b.byteLength),
    );
    const pdf = await captureDownload(page, () =>
      clickButton(page, /Download signed PDF \(1 stamp\)/),
    );
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(1);
    expect(pdf.byteLength).toBeGreaterThan(inputSize); // an image stamp was embedded
    assertClean();
  });

  test('typed signature → download a valid PDF', async ({ page }) => {
    await page.goto('/pdf-sign');
    await dropFixtures(page, ['text-1p.pdf']);
    await page.locator('[role=tab]', { hasText: 'Type' }).click();
    await page.getByPlaceholder(/Alex Rivera/).fill('Alex Rivera');
    await clickButton(page, /^Use this signature$/);
    await expect(page.locator('.sig-preview img')).toHaveCount(1);
    // placing mode starts automatically on "Use this signature"
    const stage = page.locator('.stage[data-page="1"]');
    const sbox = (await stage.boundingBox())!;
    await page.mouse.click(sbox.x + 80, sbox.y + sbox.height * 0.8);
    await expect(page.locator('.stamp')).toHaveCount(1);
    const pdf = await captureDownload(page, () =>
      clickButton(page, /Download signed PDF \(1 stamp\)/),
    );
    expect((await pdfInfo(pdf)).pages).toHaveLength(1);
  });

  test('signature upload tab: drop a PNG → preview appears', async ({ page }) => {
    await page.goto('/pdf-sign');
    await dropFixtures(page, ['text-1p.pdf']);
    await page.locator('[role=tab]', { hasText: 'Upload' }).click();
    // a second dropzone is now the upload one — target it specifically
    await page.evaluate(async () => {
      const c = document.createElement('canvas');
      c.width = 300;
      c.height = 100;
      const ctx = c.getContext('2d')!;
      ctx.strokeStyle = '#111';
      ctx.lineWidth = 6;
      ctx.beginPath();
      ctx.moveTo(10, 50);
      ctx.bezierCurveTo(80, 10, 150, 90, 290, 40);
      ctx.stroke();
      const blob = await new Promise<Blob | null>((r) => c.toBlob(r, 'image/png'));
      const dt = new DataTransfer();
      dt.items.add(new File([blob!], 'sig.png', { type: 'image/png' }));
      // the upload dropzone is the one inside the signature panel (last on page)
      const zones = document.querySelectorAll('.dropzone');
      const target = zones[zones.length - 1] as HTMLElement;
      target.dispatchEvent(
        new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer: dt }),
      );
    });
    await expect(page.locator('.sig-preview img')).toHaveCount(1);
  });

  test('encrypted PDF → friendly error', async ({ page }) => {
    const assertClean = expectClean(page);
    await page.goto('/pdf-sign');
    await dropFixtures(page, ['encrypted.pdf']);
    await expect(page.locator('.error-card')).toBeVisible();
    assertClean();
  });
});

/* ------------------------------------------------------------------ */
/* 10. Resizing mid-flow                                               */
/* ------------------------------------------------------------------ */

test.describe('resizing mid-flow', () => {
  test('merge at 1280 → drop 3 → resize 360 (layout intact, reorder works) → resize 768 → merge completes', async ({
    page,
  }) => {
    const assertClean = expectClean(page);
    await page.setViewportSize({ width: 1280, height: 900 });
    await page.goto('/pdf-merge');
    await dropFixtures(page, ['text-1p.pdf', 'text-5p.pdf', 'landscape-1p.pdf']);
    await expectRows(page, 3);
    await noHOverflow(page);

    // shrink to mobile
    await page.setViewportSize({ width: 360, height: 740 });
    await page.waitForTimeout(150);
    await noHOverflow(page);
    await expect(page.locator('ul.filelist .file-row')).toHaveCount(3);
    // reorder still works at mobile width
    await moveRow(page, 0, 'down');
    expect(await rowNames(page)).toEqual(['text-5p.pdf', 'text-1p.pdf', 'landscape-1p.pdf']);

    // back to tablet and finish the merge
    await page.setViewportSize({ width: 768, height: 1024 });
    await page.waitForTimeout(150);
    await noHOverflow(page);
    const pdf = await captureDownload(page, () =>
      clickButton(page, /^Merge 3 files into one PDF$/),
    );
    const info = await pdfInfo(pdf);
    expect(info.pages).toHaveLength(7);
    expect(info.pages[0]!.text).toContain('MARK-P1');
    assertClean();
  });
});
