/**
 * Per-route SEO metadata + JSON-LD structured data.
 *
 * Each tool page gets a title aimed at its search query, a description
 * with the privacy hook, and a SoftwareApplication + FAQPage JSON-LD block.
 * Rendered during prerendering so crawlers see the full document.
 */
import { site, siteUrl } from './config';

export interface RouteMeta {
  title: string;
  description: string;
  /** Open Graph image — generated by scripts/og-image.mjs. */
  image?: string;
}

const ogImage = `${siteUrl}/og.png`;

export const routeMeta: Record<string, RouteMeta> = {
  '/': {
    title: `${site.name} — Free, Private PDF Tools (100% in Your Browser)`,
    description:
      'Compress, convert and sign PDFs for free. Image to PDF, PDF to image, PDF compress and sign/fill — ' +
      'everything runs in your browser. No uploads, no accounts, your file never leaves your device.',
    image: ogImage,
  },
  '/pdf-compress': {
    title: 'Compress PDF Online — Free, Private, No Upload | PDFBoogie',
    description:
      'Reduce PDF file size in your browser with a lossless optimizer or a strong re-encode. ' +
      'Free PDF compress tool: no upload, no watermark, works on any device.',
    image: ogImage,
  },
  '/image-to-pdf': {
    title: 'Image to PDF Online — JPG, PNG, WebP to PDF (Private) | PDFBoogie',
    description:
      'Convert images to PDF for free in your browser. Combine JPG, PNG, WebP, GIF, BMP and AVIF into one ' +
      'PDF with A4/Letter pages or fit-to-image sizing. No upload — 100% client-side.',
    image: ogImage,
  },
  '/pdf-to-image': {
    title: 'PDF to Image Online — PDF to JPG/PNG (Private, No Upload) | PDFBoogie',
    description:
      'Convert PDF pages to JPG, PNG or WebP in your browser. Pick the resolution, take one page or all ' +
      'pages as a ZIP. Free and private: nothing is uploaded.',
    image: ogImage,
  },
  '/pdf-sign': {
    title: 'Sign PDF Online — Add Signature & Fill PDF Forms (Private) | PDFBoogie',
    description:
      'Add a drawn or typed signature to a PDF and fill form fields — entirely in your browser. ' +
      'Free, no upload, no account. Works on any device.',
    image: ogImage,
  },
  '/pdf-merge': {
    title: 'Merge PDF Online — Combine PDFs & JPGs Into One (Private) | PDFBoogie',
    description:
      'Merge multiple PDF files — and JPG/PNG images — into a single PDF in your browser. Reorder pages, ' +
      'no upload, no watermark. 100% client-side merge.',
    image: ogImage,
  },
  '/pdf-combine': {
    title: 'Combine PDF Pages — 2-Up, 4-Up, 9-Up, 16-Up (Private) | PDFBoogie',
    description:
      'Combine several PDF pages onto one sheet: pick 2-up to 16-up layouts and the pages fill as many ' +
      'sheets as needed. Runs entirely in your browser — nothing is uploaded.',
    image: ogImage,
  },
  '/pdf-to-doc': {
    title: 'Convert PDF to DOCX Online — PDF to Word / ODT (Private) | PDFBoogie',
    description:
      'Convert a PDF to an editable Word (.docx) or OpenDocument (.odt) file in your browser. ' +
      'Text, headings and basic styles are rebuilt client-side — no upload, no account.',
    image: ogImage,
  },
  '/privacy': {
    title: `Privacy — ${site.name}`,
    description:
      'How PDFBoogie works: all PDF processing happens locally in your browser. ' +
      'Nothing is uploaded, stored or transmitted. Read the full privacy policy.',
  },
};

export function jsonLdFor(path: string): object[] {
  const url = `${siteUrl}${path}`;
  const crumb = {
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'Home', item: siteUrl },
      ...(path !== '/'
        ? [{ '@type': 'ListItem', position: 2, name: path.slice(1).replace(/-/g, ' '), item: url }]
        : []),
    ],
  };

  if (path === '/') {
    return [
      {
        '@type': 'WebSite',
        name: site.name,
        url: siteUrl,
        description: site.description,
      },
      crumb,
    ];
  }

  const toolName = path.slice(1).replace(/-/g, ' ');
  const faqs: Record<string, { q: string; a: string }[]> = {
    '/pdf-compress': [
      {
        q: 'Is compressing my PDF safe and private?',
        a: 'Yes. The compression runs entirely in your browser using WebAssembly and web APIs. Your PDF is never uploaded to a server.',
      },
      {
        q: 'Does lossless compression change my PDF?',
        a: 'No. Lossless mode re-saves the document with internal structural optimizations (object and cross-reference streams). Every page renders exactly the same; only the file size drops.',
      },
      {
        q: 'What does strong compression do differently?',
        a: 'Strong mode re-renders each page as an optimized image. It often compresses more aggressively, but text is no longer selectable in the result.',
      },
    ],
    '/image-to-pdf': [
      {
        q: 'Which image formats can I convert to PDF?',
        a: 'JPG, PNG, WebP, GIF, BMP and AVIF — everything your browser can open. You can combine multiple images into a single PDF.',
      },
      {
        q: 'Are my images uploaded to a server?',
        a: 'No. The conversion happens in your browser; your images never leave your device.',
      },
      {
        q: 'Can I set the page size of the PDF?',
        a: 'Yes — fit-to-image (each page matches the image) or A4, Letter and Legal with adjustable margins.',
      },
    ],
    '/pdf-to-image': [
      {
        q: 'Which image formats can I export?',
        a: 'PNG (lossless), JPEG and WebP. Multi-page PDFs can be downloaded as a single ZIP archive.',
      },
      {
        q: 'Is the PDF uploaded anywhere?',
        a: 'No. Pages are rendered locally by Mozilla PDF.js in your browser and exported straight to your downloads.',
      },
      {
        q: 'Can I choose the image resolution?',
        a: 'Yes. Pick 96, 150, 220 or 300 DPI, and an export quality for JPEG/WebP.',
      },
    ],
    '/pdf-merge': [
      {
        q: 'Can I merge PDFs without uploading them?',
        a: 'Yes. PDFBoogie merges entirely in your browser using pdf-lib — your files never leave your device.',
      },
      {
        q: 'Can I merge images into a PDF along with PDF files?',
        a: 'Yes. Drop PDFs and images (JPG, PNG, WebP and more) together; images are added as pages in the order you arrange them.',
      },
      {
        q: 'Is the content quality preserved when merging?',
        a: 'PDF pages are copied exactly — vectors and text stay selectable. Images keep their original encoding when possible (JPEG fast path).',
      },
    ],
    '/pdf-combine': [
      {
        q: 'What does “combine pages” mean?',
        a: 'You select pages from a PDF and choose a grid per sheet (2-up, 4-up, 9-up or 16-up). The selected pages flow onto as many sheets as needed — for example 13 pages at 4-up become 4 sheets.',
      },
      {
        q: 'Is anything uploaded?',
        a: 'No. Everything runs in your browser.',
      },
      {
        q: 'Is the result vector or image-based?',
        a: 'Pages are placed at high resolution, so the combined sheets are image-based. Text on the sheets is not selectable; the original pages are unchanged when you open the source file.',
      },
    ],
    '/pdf-sign': [
      {
        q: 'How do I sign a PDF for free?',
        a: 'Draw your signature with a mouse or finger, type it, or upload an image. Then click where it should go on the page and download the result.',
      },
      {
        q: 'Can I fill PDF form fields?',
        a: 'Yes. Standard (AcroForm) text fields, checkboxes, radio buttons and dropdowns are listed and can be filled right in the browser.',
      },
      {
        q: 'Is my signed PDF uploaded to a server?',
        a: 'No. Signing and form filling run entirely in your browser.',
      },
    ],
    '/pdf-to-doc': [
      {
        q: 'Can I convert a PDF to Word (.docx) without uploading it?',
        a: 'Yes. PDFBoogie extracts the text in your browser and rebuilds it as a .docx (Word) or .odt (OpenDocument/LibreOffice) file. Your PDF never leaves your device.',
      },
      {
        q: 'Is the layout preserved in the converted document?',
        a: 'Text flows in reading order with paragraphs, headings, bold and italic styles, plus page breaks. Tables, images and complex multi-column layouts are not reconstructed, because a PDF stores glyph positions rather than a document structure.',
      },
      {
        q: 'Which formats can I export to?',
        a: '.docx (Microsoft Word, WPS, LibreOffice) and .odt (LibreOffice, OpenOffice, Google Docs import).',
      },
    ],
  };

  const blocks: object[] = [
    {
      '@type': 'SoftwareApplication',
      name: `${site.name} — ${toolName}`,
      operatingSystem: 'Web (any modern browser)',
      applicationCategory: 'UtilityApplication',
      url,
      description: routeMeta[path]?.description ?? '',
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    },
    crumb,
  ];

  const pageFaqs = faqs[path];
  if (pageFaqs) {
    blocks.push({
      '@type': 'FAQPage',
      mainEntity: pageFaqs.map((f) => ({
        '@type': 'Question',
        name: f.q,
        acceptedAnswer: { '@type': 'Answer', text: f.a },
      })),
    });
  }

  return blocks;
}
